/* Pixel sprite manifest + renderer for nyanwan-rx.
 *
 * Sheets live at assets/sprites/<cat>/<variant>/<anim>.png — horizontal
 * strips of square frames. SPRITES is generated by scanning the sheets
 * (anims: name -> frame count; cx/foot/ch describe where the artwork sits
 * inside the padded frame, measured from the first idle frame's alpha).
 *
 * spriteImg() renders one as an animated element compatible with the
 * .sprite emoji placeholders in game.js — same (x%, y%) anchor, feet
 * planted where an emoji's feet would land — so the two mix freely.
 * Returns null for unknown variants; callers fall back to emoji.
 */

export interface SpriteDef {
  cat: "pets" | "humans";
  frame: number;
  scale: number;
  cx: number;
  cw: number;
  foot: number;
  ch: number;
  anims: Record<string, number>;
}

export interface SpriteOpts {
  enter?: boolean;
  status?: string;
  flip?: boolean;
  scale?: number;
  pose?: string;
}

export const SPRITES: Record<string, SpriteDef> = {
  "bat-albino": { cat: "pets", frame: 32, scale: 4, cx: 16, cw: 12, foot: 19, ch: 9, anims: { "fly": 4 } },
  "bat-fire": { cat: "pets", frame: 32, scale: 4, cx: 16, cw: 12, foot: 19, ch: 9, anims: { "fly": 4 } },
  "bat-root": { cat: "pets", frame: 32, scale: 4, cx: 16, cw: 12, foot: 19, ch: 9, anims: { "fly": 4 } },
  "bat-standard": { cat: "pets", frame: 32, scale: 4, cx: 16, cw: 12, foot: 19, ch: 9, anims: { "fly": 4 } },
  "bat-vampire": { cat: "pets", frame: 32, scale: 4, cx: 16, cw: 12, foot: 19, ch: 9, anims: { "fly": 4 } },
  "bat-zombie": { cat: "pets", frame: 32, scale: 4, cx: 16, cw: 12, foot: 19, ch: 9, anims: { "fly": 4 } },
  "bibarel": { cat: "pets", frame: 36, scale: 2, cx: 18, cw: 36, foot: 36, ch: 32, anims: { "idle": 4 } },
  "bidoof": { cat: "pets", frame: 24, scale: 3, cx: 12, cw: 24, foot: 24, ch: 22, anims: { "idle": 4 } },
  "bird-crow": { cat: "pets", frame: 32, scale: 3, cx: 12, cw: 19, foot: 32, ch: 17, anims: { "idle": 4, "walk": 6 } },
  "bird-pigeon": { cat: "pets", frame: 32, scale: 4, cx: 11, cw: 14, foot: 32, ch: 13, anims: { "idle": 4, "walk": 6 } },
  "blastoise": { cat: "pets", frame: 39, scale: 2, cx: 19, cw: 37, foot: 39, ch: 37, anims: { "idle": 4 } },
  "blissey": { cat: "pets", frame: 62, scale: 2, cx: 31, cw: 62, foot: 62, ch: 33, anims: { "idle": 4 } },
  "boar-gray": { cat: "pets", frame: 17, scale: 4, cx: 9, cw: 16, foot: 17, ch: 15, anims: { "idle": 2 } },
  "boar-red": { cat: "pets", frame: 17, scale: 4, cx: 9, cw: 16, foot: 17, ch: 15, anims: { "idle": 2 } },
  "bulbasaur": { cat: "pets", frame: 25, scale: 2, cx: 12, cw: 24, foot: 25, ch: 24, anims: { "idle": 4 } },
  "cat-01": { cat: "pets", frame: 50, scale: 4, cx: 25, cw: 19, foot: 32, ch: 14, anims: { "idle": 10, "itch": 2, "lick": 5, "lick-2": 5, "lie": 8, "meow": 4, "run": 8, "sit": 1, "sleep": 1, "sleep-2": 1, "stretch": 13, "walk": 8 } },
  "cat-02": { cat: "pets", frame: 50, scale: 4, cx: 25, cw: 19, foot: 32, ch: 14, anims: { "idle": 10, "itch": 2, "lick": 5, "lick-2": 5, "lie": 8, "meow": 4, "run": 8, "sit": 1, "sleep": 1, "sleep-2": 1, "stretch": 13, "walk": 8 } },
  "cat-03": { cat: "pets", frame: 50, scale: 4, cx: 25, cw: 19, foot: 32, ch: 14, anims: { "idle": 10, "lick": 5, "lick-2": 5, "lie": 8, "meow": 4, "run": 8, "sit": 1, "sleep": 1, "sleep-2": 1, "stretch": 13, "walk": 8 } },
  "cat-04": { cat: "pets", frame: 50, scale: 4, cx: 26, cw: 20, foot: 32, ch: 16, anims: { "idle": 10, "itch": 2, "lick": 5, "lick-2": 5, "lie": 8, "meow": 4, "run": 8, "sit": 1, "sleep": 1, "sleep-2": 1, "stretch": 13, "walk": 8 } },
  "cat-05": { cat: "pets", frame: 50, scale: 4, cx: 25, cw: 19, foot: 32, ch: 16, anims: { "idle": 10, "itch": 2, "lick": 5, "lick-2": 5, "lie": 8, "meow": 4, "run": 8, "sit": 1, "sleep": 1, "sleep-2": 1, "stretch": 13, "walk": 8 } },
  "cat-06": { cat: "pets", frame: 50, scale: 4, cx: 25, cw: 19, foot: 32, ch: 14, anims: { "idle": 10, "itch": 2, "lick": 5, "lick-2": 5, "lie": 8, "meow": 4, "run": 8, "sit": 1, "sleep": 1, "sleep-2": 1, "stretch": 13, "walk": 8 } },
  "cat-07": { cat: "pets", frame: 48, scale: 3, cx: 19, cw: 28, foot: 48, ch: 23, anims: { "idle": 4, "walk": 6 } },
  "cat-08": { cat: "pets", frame: 48, scale: 3, cx: 18, cw: 24, foot: 48, ch: 19, anims: { "idle": 4, "walk": 6 } },
  "cat-black": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 15, foot: 16, ch: 15, anims: { "idle": 2 } },
  "cat-brown": { cat: "pets", frame: 22, scale: 4, cx: 11, cw: 20, foot: 22, ch: 16, anims: { "idle": 2 } },
  "cat-cyclops": { cat: "pets", frame: 16, scale: 4, cx: 7, cw: 13, foot: 13, ch: 11, anims: { "idle": 2 } },
  "cat-gray": { cat: "pets", frame: 17, scale: 4, cx: 8, cw: 16, foot: 17, ch: 14, anims: { "idle": 2 } },
  "cat-orange": { cat: "pets", frame: 22, scale: 4, cx: 11, cw: 20, foot: 22, ch: 16, anims: { "idle": 2 } },
  "cat-tabby": { cat: "pets", frame: 16, scale: 4, cx: 7, cw: 13, foot: 13, ch: 11, anims: { "idle": 2 } },
  "cat-white": { cat: "pets", frame: 17, scale: 4, cx: 8, cw: 16, foot: 17, ch: 14, anims: { "idle": 2 } },
  "cat-yellow": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 15, foot: 16, ch: 15, anims: { "idle": 2 } },
  "chicken-black": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 16, foot: 16, ch: 16, anims: { "idle": 2 } },
  "chicken-brown": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 16, foot: 16, ch: 16, anims: { "idle": 2 } },
  "chicken-cute": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 14, foot: 16, ch: 13, anims: { "idle": 2 } },
  "chicken-white": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 16, foot: 16, ch: 16, anims: { "idle": 2 } },
  "cleffa": { cat: "pets", frame: 35, scale: 4, cx: 17, cw: 16, foot: 35, ch: 16, anims: { "idle": 4 } },
  "cow-white": { cat: "pets", frame: 24, scale: 4, cx: 12, cw: 16, foot: 24, ch: 16, anims: { "idle": 2, "run": 2 } },
  "ditto": { cat: "pets", frame: 18, scale: 4, cx: 9, cw: 18, foot: 18, ch: 16, anims: { "idle": 4 } },
  "dog-akita": { cat: "pets", frame: 100, scale: 4, cx: 50, cw: 19, foot: 58, ch: 15, anims: { "bark": 3, "idle": 10, "itch": 2, "lick": 4, "lick-2": 4, "lie": 7, "run": 8, "sit": 1, "sleep": 1, "stretch": 10, "walk": 8 } },
  "dog-black": { cat: "pets", frame: 21, scale: 4, cx: 10, cw: 19, foot: 21, ch: 16, anims: { "idle": 2 } },
  "dog-brown": { cat: "pets", frame: 18, scale: 4, cx: 10, cw: 16, foot: 18, ch: 15, anims: { "idle": 2 } },
  "dog-doberman": { cat: "pets", frame: 48, scale: 2, cx: 18, cw: 29, foot: 48, ch: 31, anims: { "idle": 4, "walk": 6 } },
  "dog-golden-retriever": { cat: "pets", frame: 100, scale: 3, cx: 50, cw: 33, foot: 61, ch: 22, anims: { "bark": 3, "idle": 10, "itch": 2, "lick": 4, "lick-2": 4, "lie": 7, "run": 8, "sit": 1, "sleep": 1, "stretch": 10, "walk": 8 } },
  "dog-great-dane": { cat: "pets", frame: 100, scale: 2, cx: 50, cw: 39, foot: 67, ch: 34, anims: { "bark": 3, "idle": 10, "itch": 2, "lick": 4, "lick-2": 4, "lie": 7, "run": 8, "sit": 1, "sleep": 1, "stretch": 10, "walk": 8 } },
  "dog-husky": { cat: "pets", frame: 100, scale: 2, cx: 50, cw: 33, foot: 62, ch: 24, anims: { "bark": 3, "idle": 10, "itch": 2, "lick": 4, "lick-2": 4, "lie": 7, "run": 8, "sit": 1, "sleep": 1, "stretch": 10, "walk": 8 } },
  "dog-pink": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 12, foot: 13, ch: 12, anims: { "idle": 2 } },
  "dog-rust": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 12, foot: 13, ch: 10, anims: { "idle": 2 } },
  "dog-saint-bernard": { cat: "pets", frame: 100, scale: 2, cx: 50, cw: 43, foot: 65, ch: 29, anims: { "bark": 3, "idle": 10, "itch": 2, "lick": 4, "lick-2": 4, "lie": 7, "run": 8, "sit": 1, "sleep": 1, "stretch": 10, "walk": 8 } },
  "dog-schnauzer": { cat: "pets", frame: 100, scale: 3, cx: 50, cw: 27, foot: 62, ch: 23, anims: { "bark": 3, "idle": 10, "itch": 2, "lick": 4, "lick-2": 4, "lie": 7, "run": 8, "sit": 1, "sleep": 1, "stretch": 10, "walk": 8 } },
  "dog-scruffy": { cat: "pets", frame: 18, scale: 4, cx: 9, cw: 16, foot: 18, ch: 16, anims: { "idle": 2 } },
  "dog-shiba": { cat: "pets", frame: 48, scale: 2, cx: 20, cw: 29, foot: 48, ch: 25, anims: { "idle": 4, "walk": 6 } },
  "dog-spaniel": { cat: "pets", frame: 18, scale: 4, cx: 10, cw: 16, foot: 18, ch: 15, anims: { "idle": 2 } },
  "dog-white": { cat: "pets", frame: 18, scale: 4, cx: 9, cw: 16, foot: 18, ch: 16, anims: { "idle": 2 } },
  "dog-yellow": { cat: "pets", frame: 21, scale: 4, cx: 10, cw: 19, foot: 21, ch: 16, anims: { "idle": 2 } },
  "donkey-gray": { cat: "pets", frame: 23, scale: 4, cx: 11, cw: 16, foot: 23, ch: 16, anims: { "idle": 2, "run": 2 } },
  "fish-red": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 15, foot: 12, ch: 8, anims: { "idle": 2 } },
  "fish-white": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 15, foot: 12, ch: 8, anims: { "idle": 2 } },
  "fish-yellow": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 14, foot: 12, ch: 8, anims: { "idle": 2 } },
  "frog-bandana": { cat: "pets", frame: 16, scale: 4, cx: 7, cw: 11, foot: 13, ch: 10, anims: { "idle": 2 } },
  "frog-blue-blue": { cat: "pets", frame: 48, scale: 4, cx: 21, cw: 21, foot: 33, ch: 16, anims: { "idle": 8 } },
  "frog-blue-brown": { cat: "pets", frame: 48, scale: 4, cx: 21, cw: 21, foot: 33, ch: 16, anims: { "idle": 8 } },
  "frog-green-blue": { cat: "pets", frame: 48, scale: 4, cx: 21, cw: 21, foot: 33, ch: 16, anims: { "idle": 8 } },
  "frog-green-brown": { cat: "pets", frame: 48, scale: 4, cx: 21, cw: 21, foot: 33, ch: 16, anims: { "idle": 8 } },
  "frog-purple-blue": { cat: "pets", frame: 48, scale: 4, cx: 21, cw: 21, foot: 33, ch: 16, anims: { "idle": 8 } },
  "frog-purple-white": { cat: "pets", frame: 48, scale: 4, cx: 21, cw: 21, foot: 33, ch: 16, anims: { "idle": 8 } },
  "gabite": { cat: "pets", frame: 29, scale: 2, cx: 14, cw: 27, foot: 29, ch: 29, anims: { "idle": 4 } },
  "garchomp": { cat: "pets", frame: 40, scale: 1, cx: 19, cw: 39, foot: 40, ch: 40, anims: { "idle": 4 } },
  "gastly": { cat: "pets", frame: 32, scale: 2, cx: 16, cw: 32, foot: 32, ch: 31, anims: { "idle": 4 } },
  "gengar": { cat: "pets", frame: 29, scale: 2, cx: 14, cw: 24, foot: 29, ch: 28, anims: { "idle": 4 } },
  "geodude": { cat: "pets", frame: 37, scale: 2, cx: 18, cw: 34, foot: 37, ch: 24, anims: { "idle": 4 } },
  "gible": { cat: "pets", frame: 28, scale: 2, cx: 14, cw: 24, foot: 28, ch: 28, anims: { "idle": 4 } },
  "girafarig": { cat: "pets", frame: 38, scale: 2, cx: 19, cw: 28, foot: 38, ch: 38, anims: { "idle": 4 } },
  "golem": { cat: "pets", frame: 32, scale: 2, cx: 15, cw: 31, foot: 32, ch: 31, anims: { "idle": 4 } },
  "graveler": { cat: "pets", frame: 32, scale: 2, cx: 15, cw: 31, foot: 32, ch: 28, anims: { "idle": 4 } },
  "hamster-brown": { cat: "pets", frame: 15, scale: 4, cx: 7, cw: 12, foot: 15, ch: 13, anims: { "idle": 2 } },
  "hamster-cream": { cat: "pets", frame: 15, scale: 4, cx: 8, cw: 13, foot: 15, ch: 14, anims: { "idle": 2 } },
  "hamster-dark": { cat: "pets", frame: 15, scale: 4, cx: 8, cw: 12, foot: 15, ch: 13, anims: { "idle": 2 } },
  "hamster-gray": { cat: "pets", frame: 15, scale: 4, cx: 8, cw: 13, foot: 15, ch: 14, anims: { "idle": 2 } },
  "happiny": { cat: "pets", frame: 24, scale: 2, cx: 12, cw: 18, foot: 24, ch: 24, anims: { "idle": 4 } },
  "hariyama": { cat: "pets", frame: 45, scale: 1, cx: 22, cw: 45, foot: 45, ch: 45, anims: { "idle": 4 } },
  "haunter": { cat: "pets", frame: 35, scale: 2, cx: 17, cw: 35, foot: 35, ch: 35, anims: { "idle": 4 } },
  "hoothoot": { cat: "pets", frame: 26, scale: 2, cx: 13, cw: 24, foot: 26, ch: 24, anims: { "idle": 4 } },
  "hoppip": { cat: "pets", frame: 21, scale: 3, cx: 10, cw: 18, foot: 21, ch: 21, anims: { "idle": 4 } },
  "horsea": { cat: "pets", frame: 20, scale: 3, cx: 10, cw: 16, foot: 20, ch: 20, anims: { "idle": 4 } },
  "hyena": { cat: "pets", frame: 48, scale: 2, cx: 29, cw: 35, foot: 48, ch: 28, anims: { "idle": 4, "walk": 6 } },
  "hyena-brown": { cat: "pets", frame: 14, scale: 4, cx: 7, cw: 12, foot: 14, ch: 13, anims: { "idle": 2 } },
  "hyena-gray": { cat: "pets", frame: 14, scale: 4, cx: 8, cw: 12, foot: 14, ch: 13, anims: { "idle": 2 } },
  "ivysaur": { cat: "pets", frame: 32, scale: 2, cx: 15, cw: 31, foot: 32, ch: 32, anims: { "idle": 4 } },
  "jumpluff": { cat: "pets", frame: 27, scale: 2, cx: 13, cw: 25, foot: 27, ch: 24, anims: { "idle": 4 } },
  "kabuto": { cat: "pets", frame: 22, scale: 3, cx: 10, cw: 21, foot: 22, ch: 17, anims: { "idle": 4 } },
  "kabutops": { cat: "pets", frame: 32, scale: 2, cx: 15, cw: 29, foot: 32, ch: 32, anims: { "idle": 4 } },
  "kingdra": { cat: "pets", frame: 46, scale: 1, cx: 22, cw: 33, foot: 46, ch: 44, anims: { "idle": 4 } },
  "kingler": { cat: "pets", frame: 36, scale: 2, cx: 17, cw: 35, foot: 36, ch: 34, anims: { "idle": 4 } },
  "koffing": { cat: "pets", frame: 25, scale: 3, cx: 12, cw: 19, foot: 25, ch: 21, anims: { "idle": 4 } },
  "krabby": { cat: "pets", frame: 26, scale: 3, cx: 13, cw: 26, foot: 26, ch: 22, anims: { "idle": 4 } },
  "lapras": { cat: "pets", frame: 51, scale: 1, cx: 25, cw: 44, foot: 51, ch: 51, anims: { "idle": 4 } },
  "lion-cub": { cat: "pets", frame: 16, scale: 4, cx: 7, cw: 12, foot: 13, ch: 11, anims: { "idle": 2 } },
  "lion-cub-pink": { cat: "pets", frame: 16, scale: 4, cx: 7, cw: 12, foot: 13, ch: 11, anims: { "idle": 2 } },
  "lion-orange": { cat: "pets", frame: 30, scale: 3, cx: 15, cw: 16, foot: 30, ch: 23, anims: { "idle": 2, "run": 2 } },
  "lion-red": { cat: "pets", frame: 30, scale: 3, cx: 15, cw: 16, foot: 30, ch: 23, anims: { "idle": 2, "run": 2 } },
  "lion-white": { cat: "pets", frame: 30, scale: 3, cx: 15, cw: 16, foot: 30, ch: 23, anims: { "idle": 2, "run": 2 } },
  "lion-yellow": { cat: "pets", frame: 30, scale: 3, cx: 15, cw: 16, foot: 30, ch: 23, anims: { "idle": 2, "run": 2 } },
  "lioness": { cat: "pets", frame: 30, scale: 3, cx: 15, cw: 16, foot: 30, ch: 23, anims: { "idle": 2, "run": 2 } },
  "lioness-gold": { cat: "pets", frame: 30, scale: 3, cx: 15, cw: 16, foot: 30, ch: 23, anims: { "idle": 2, "run": 2 } },
  "lombre": { cat: "pets", frame: 27, scale: 2, cx: 13, cw: 19, foot: 27, ch: 27, anims: { "idle": 4 } },
  "lotad": { cat: "pets", frame: 22, scale: 3, cx: 11, cw: 22, foot: 22, ch: 20, anims: { "idle": 4 } },
  "ludicolo": { cat: "pets", frame: 32, scale: 2, cx: 16, cw: 28, foot: 32, ch: 32, anims: { "idle": 4 } },
  "makuhita": { cat: "pets", frame: 31, scale: 2, cx: 15, cw: 20, foot: 31, ch: 30, anims: { "idle": 4 } },
  "mankey": { cat: "pets", frame: 29, scale: 2, cx: 14, cw: 28, foot: 29, ch: 27, anims: { "idle": 4 } },
  "mantine": { cat: "pets", frame: 48, scale: 1, cx: 24, cw: 48, foot: 48, ch: 46, anims: { "idle": 4 } },
  "mantyke": { cat: "pets", frame: 27, scale: 2, cx: 13, cw: 23, foot: 27, ch: 27, anims: { "idle": 4 } },
  "marshtomp": { cat: "pets", frame: 25, scale: 2, cx: 12, cw: 23, foot: 25, ch: 24, anims: { "idle": 4 } },
  "moltres": { cat: "pets", frame: 63, scale: 1, cx: 31, cw: 54, foot: 63, ch: 63, anims: { "idle": 4 } },
  "monkey-black": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 16, foot: 13, ch: 12, anims: { "idle": 2 } },
  "monkey-brown": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 16, foot: 13, ch: 12, anims: { "idle": 2 } },
  "monkey-gray": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 16, foot: 13, ch: 11, anims: { "idle": 2 } },
  "mudkip": { cat: "pets", frame: 43, scale: 3, cx: 21, cw: 21, foot: 43, ch: 19, anims: { "idle": 4 } },
  "natu": { cat: "pets", frame: 23, scale: 3, cx: 11, cw: 18, foot: 23, ch: 23, anims: { "idle": 4 } },
  "noctowl": { cat: "pets", frame: 43, scale: 1, cx: 21, cw: 43, foot: 43, ch: 39, anims: { "idle": 4 } },
  "oshawott": { cat: "pets", frame: 36, scale: 2, cx: 17, cw: 29, foot: 36, ch: 36, anims: { "idle": 5 } },
  "parrot-blue": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 16, foot: 16, ch: 15, anims: { "idle": 2 } },
  "parrot-red": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 16, foot: 16, ch: 15, anims: { "idle": 2 } },
  "pichu": { cat: "pets", frame: 23, scale: 3, cx: 11, cw: 17, foot: 23, ch: 22, anims: { "idle": 4 } },
  "pig-black": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 16, foot: 15, ch: 13, anims: { "idle": 2 } },
  "pig-pink": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 16, foot: 15, ch: 13, anims: { "idle": 2 } },
  "pig-red": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 16, foot: 15, ch: 13, anims: { "idle": 2 } },
  "pony-black": { cat: "pets", frame: 23, scale: 4, cx: 11, cw: 16, foot: 23, ch: 16, anims: { "idle": 2, "run": 2 } },
  "pony-brown": { cat: "pets", frame: 23, scale: 4, cx: 11, cw: 16, foot: 23, ch: 16, anims: { "idle": 2, "run": 2 } },
  "primeape": { cat: "pets", frame: 32, scale: 2, cx: 15, cw: 27, foot: 32, ch: 32, anims: { "idle": 4 } },
  "raccoon": { cat: "pets", frame: 16, scale: 4, cx: 8, cw: 16, foot: 13, ch: 11, anims: { "idle": 2 } },
  "rat-01": { cat: "pets", frame: 32, scale: 4, cx: 13, cw: 25, foot: 32, ch: 9, anims: { "idle": 4, "walk": 4 } },
  "rat-02": { cat: "pets", frame: 32, scale: 4, cx: 13, cw: 18, foot: 32, ch: 6, anims: { "idle": 4, "walk": 4 } },
  "scorpion": { cat: "pets", frame: 48, scale: 3, cx: 30, cw: 32, foot: 48, ch: 23, anims: { "idle": 4, "walk": 4 } },
  "seadra": { cat: "pets", frame: 31, scale: 2, cx: 15, cw: 30, foot: 31, ch: 28, anims: { "idle": 4 } },
  "skiploom": { cat: "pets", frame: 24, scale: 3, cx: 12, cw: 20, foot: 24, ch: 21, anims: { "idle": 4 } },
  "snake": { cat: "pets", frame: 48, scale: 4, cx: 33, cw: 28, foot: 48, ch: 15, anims: { "idle": 4, "walk": 4 } },
  "snivy": { cat: "pets", frame: 39, scale: 2, cx: 19, cw: 29, foot: 39, ch: 33, anims: { "idle": 6 } },
  "swampert": { cat: "pets", frame: 78, scale: 2, cx: 39, cw: 32, foot: 78, ch: 38, anims: { "idle": 4 } },
  "venusaur": { cat: "pets", frame: 46, scale: 1, cx: 22, cw: 45, foot: 46, ch: 42, anims: { "idle": 4 } },
  "vulture": { cat: "pets", frame: 48, scale: 2, cx: 30, cw: 27, foot: 48, ch: 26, anims: { "idle": 4, "walk": 4 } },
  "weezing": { cat: "pets", frame: 31, scale: 2, cx: 15, cw: 31, foot: 31, ch: 29, anims: { "idle": 4 } },
  "xatu": { cat: "pets", frame: 47, scale: 1, cx: 23, cw: 22, foot: 47, ch: 45, anims: { "idle": 4 } },
  "biker": { cat: "humans", frame: 48, scale: 2, cx: 13, cw: 19, foot: 48, ch: 34, anims: { "attack": 6, "attack-2": 8, "attack-3": 8, "double-jump": 6, "idle": 4, "jump": 4, "punch": 6, "run": 6, "run-attack": 6 } },
  "cyborg": { cat: "humans", frame: 48, scale: 2, cx: 12, cw: 19, foot: 48, ch: 35, anims: { "attack": 6, "attack-2": 8, "attack-3": 8, "double-jump": 6, "idle": 4, "jump": 4, "punch": 6, "run": 6, "run-attack": 6 } },
  "evil-wizard": { cat: "humans", frame: 140, scale: 1, cx: 73, cw: 33, foot: 97, ch: 53, anims: { "idle": 10, "run": 8, "walk": 8 } },
  "huntress": { cat: "humans", frame: 100, scale: 2, cx: 51, cw: 32, foot: 67, ch: 36, anims: { "attack": 6, "idle": 10, "run": 8 } },
  "martial-hero": { cat: "humans", frame: 126, scale: 2, cx: 68, cw: 44, foot: 82, ch: 39, anims: { "attack": 7, "attack-2": 6, "attack-3": 9, "idle": 10, "run": 8 } },
  "punk": { cat: "humans", frame: 48, scale: 2, cx: 13, cw: 17, foot: 48, ch: 34, anims: { "attack": 6, "attack-2": 8, "attack-3": 8, "double-jump": 6, "idle": 4, "jump": 4, "punch": 6, "run": 6, "run-attack": 6 } },
};

/* which sheet variants can stand in for a species; absent = emoji placeholder */
export const SPECIES_SPRITES: Record<string, string[]> = {
  dog: ["dog-golden-retriever", "dog-akita", "dog-great-dane", "dog-schnauzer",
        "dog-saint-bernard", "dog-husky", "dog-shiba", "dog-doberman",
        "dog-rust", "dog-pink", "dog-scruffy", "dog-white", "dog-spaniel",
        "dog-brown", "dog-yellow", "dog-black"],
  cat: ["cat-01", "cat-02", "cat-03", "cat-04", "cat-05", "cat-06", "cat-07", "cat-08",
        "cat-tabby", "cat-black", "cat-yellow", "cat-cyclops", "cat-orange",
        "cat-brown", "cat-white", "cat-gray"],
  bird: ["bird-crow", "bird-pigeon"],
  frog: ["frog-blue-blue", "frog-blue-brown", "frog-green-blue",
         "frog-green-brown", "frog-purple-blue", "frog-purple-white", "frog-bandana"],
  bat: ["bat-albino", "bat-fire", "bat-root", "bat-standard", "bat-vampire", "bat-zombie"],
  rat: ["rat-01", "rat-02"],
  hyena: ["hyena", "hyena-gray", "hyena-brown"],
  scorpion: ["scorpion"],
  snake: ["snake"],
  vulture: ["vulture"],
  hamster: ["hamster-cream", "hamster-brown", "hamster-dark", "hamster-gray"],
  parrot: ["parrot-blue", "parrot-red"],
  fish: ["fish-red", "fish-white", "fish-yellow"],
  pony: ["pony-black", "pony-brown"],
  pig: ["pig-black", "pig-pink", "pig-red"],
  monkey: ["monkey-black", "monkey-brown", "monkey-gray"],
  chicken: ["chicken-black", "chicken-brown", "chicken-cute", "chicken-white"],
  cow: ["cow-white"],
  donkey: ["donkey-gray"],
  lion: ["lion-orange", "lion-red", "lion-white", "lion-yellow",
         "lioness", "lioness-gold", "lion-cub", "lion-cub-pink"],
  raccoon: ["raccoon"],
  boar: ["boar-red", "boar-gray"],
  /* pocket monsters — variant ids are real pokemon names; the chart shows
   * the variant's name (Title Case) instead of the species label */
  pikachu: ["pichu"],
  squirtle: ["blastoise"],
  snivy: ["snivy"],
  oshawott: ["oshawott"],
  bidoof: ["bidoof", "bibarel"],
  bulbasaur: ["bulbasaur", "ivysaur", "venusaur"],
  cleffa: ["cleffa"],
  ditto: ["ditto"],
  gastly: ["gastly", "haunter", "gengar"],
  geodude: ["geodude", "graveler", "golem"],
  gible: ["gible", "gabite", "garchomp"],
  girafarig: ["girafarig"],
  happiny: ["happiny", "blissey"],
  hoothoot: ["hoothoot", "noctowl"],
  hoppip: ["hoppip", "skiploom", "jumpluff"],
  horsea: ["horsea", "seadra", "kingdra"],
  kabuto: ["kabuto", "kabutops"],
  koffing: ["koffing", "weezing"],
  krabby: ["krabby", "kingler"],
  lapras: ["lapras"],
  lotad: ["lotad", "lombre", "ludicolo"],
  makuhita: ["makuhita", "hariyama"],
  mankey: ["mankey", "primeape"],
  mantyke: ["mantyke", "mantine"],
  moltres: ["moltres"],
  mudkip: ["mudkip", "marshtomp", "swampert"],
  natu: ["natu", "xatu"],
};

export const HUMAN_SPRITES = Object.keys(SPRITES).filter(id => SPRITES[id].cat === "humans");

const FRAME_MS = 120; // per animation frame

/* Animated strip element. (x%, y%) matches the emoji sprites' anchor —
 * roughly the top-left of a ~40px emoji — so the artwork's feet are placed
 * at anchor + (20px, 44px), same as an emoji's feet. */
export function spriteImg(id: string, anim: string, x: number, y: number, opts: SpriteOpts = {}): string | null {
  const s = SPRITES[id];
  if (!s) return null;
  const a = s.anims[anim] ? anim : (s.anims.idle ? "idle" : Object.keys(s.anims)[0]);
  const frames = s.anims[a];
  const k = opts.scale || s.scale;
  const px = s.frame * k;
  const style = [
    `width:${px}px`, `height:${px}px`,
    `background-image:url(${import.meta.env.BASE_URL}assets/sprites/${s.cat}/${id}/${a}.png)`,
    `background-size:${frames * px}px ${px}px`,
    `--shift:${-frames * px}px`,
    `animation-duration:${frames * FRAME_MS}ms`,
    `animation-timing-function:steps(${frames})`,
    `margin-left:${Math.round(20 - s.cx * k)}px`,
    `margin-top:${Math.round(44 - s.foot * k)}px`,
    opts.flip ? "scale:-1 1" : "",
  ].join(";");
  const status = opts.status
    ? `<span class="s-status" style="top:${Math.round(44 - (s.ch * k) - 30)}px;left:${20 + Math.round(s.ch * k * 0.4)}px;right:auto">${opts.status}</span>`
    : "";
  return `<div class="sprite${opts.enter ? " enter" : ""}" style="left:${x}%;top:${y}%">
    ${status}<div class="s-px" style="${style}"></div></div>`;
}

/* Same animated strip, but as a flow-friendly inline-block cropped to the
 * artwork's content box, sized so the content is ~target px tall. Drops in
 * wherever an emoji of that font-size would go (minigame stages, HUD, …). */
export function spriteInline(id: string, target: number, anim = "idle"): string | null {
  const s = SPRITES[id];
  if (!s) return null;
  const a = s.anims[anim] ? anim : (s.anims.idle ? "idle" : Object.keys(s.anims)[0]);
  const frames = s.anims[a];
  const k = Math.max(1, Math.round(target / s.ch));
  const px = s.frame * k;
  const inner = [
    `width:${px}px`, `height:${px}px`,
    `background-image:url(${import.meta.env.BASE_URL}assets/sprites/${s.cat}/${id}/${a}.png)`,
    `background-size:${frames * px}px ${px}px`,
    `--shift:${-frames * px}px`,
    `animation-duration:${frames * FRAME_MS}ms`,
    `animation-timing-function:steps(${frames})`,
    `position:absolute`,
    `left:${Math.round(s.cw / 2 - s.cx) * k}px`,
    `top:${(s.ch - s.foot) * k}px`,
  ].join(";");
  return `<span class="s-in" style="width:${s.cw * k}px;height:${s.ch * k}px">
    <span class="s-px" style="${inner}"></span></span>`;
}
