/* Pixel sprite manifest + renderer for nyanwan-rx.
 *
 * Sheets live at assets/sprites/<cat>/<variant>/<anim>.png — horizontal
 * strips of square frames. SPRITES is generated by scanning the sheets
 * (anims: name -> frame count; cx/foot/ch describe where the artwork sits
 * inside the padded frame, measured from the first idle frame's alpha).
 *
 * spriteImg() renders one as an animated element compatible with the
 * .sprite emoji placeholders in game.js — same (x%, y%) anchor, feet
 * planted where an emoji's feet would land — so the two mix freely.
 * Returns null for unknown variants; callers fall back to emoji.
 */

export interface SpriteDef {
  cat: "pets" | "humans";
  frame: number;
  scale: number;
  cx: number;
  foot: number;
  ch: number;
  anims: Record<string, number>;
}

export interface SpriteOpts {
  enter?: boolean;
  status?: string;
  flip?: boolean;
  scale?: number;
  pose?: string;
}

export const SPRITES: Record<string, SpriteDef> = {
  "bat-albino": { cat: "pets", frame: 32, scale: 4, cx: 16, foot: 19, ch: 9, anims: { "fly": 4 } },
  "bat-fire": { cat: "pets", frame: 32, scale: 4, cx: 16, foot: 19, ch: 9, anims: { "fly": 4 } },
  "bat-root": { cat: "pets", frame: 32, scale: 4, cx: 16, foot: 19, ch: 9, anims: { "fly": 4 } },
  "bat-standard": { cat: "pets", frame: 32, scale: 4, cx: 16, foot: 19, ch: 9, anims: { "fly": 4 } },
  "bat-vampire": { cat: "pets", frame: 32, scale: 4, cx: 16, foot: 19, ch: 9, anims: { "fly": 4 } },
  "bat-zombie": { cat: "pets", frame: 32, scale: 4, cx: 16, foot: 19, ch: 9, anims: { "fly": 4 } },
  "bird-crow": { cat: "pets", frame: 32, scale: 3, cx: 12, foot: 32, ch: 17, anims: { "idle": 4, "walk": 6 } },
  "bird-pigeon": { cat: "pets", frame: 32, scale: 4, cx: 11, foot: 32, ch: 13, anims: { "idle": 4, "walk": 6 } },
  "cat-01": { cat: "pets", frame: 50, scale: 4, cx: 25, foot: 32, ch: 14, anims: { "idle": 10, "itch": 2, "lick": 5, "lick-2": 5, "lie": 8, "meow": 4, "run": 8, "sit": 1, "sleep": 1, "sleep-2": 1, "stretch": 13, "walk": 8 } },
  "cat-02": { cat: "pets", frame: 50, scale: 4, cx: 25, foot: 32, ch: 14, anims: { "idle": 10, "itch": 2, "lick": 5, "lick-2": 5, "lie": 8, "meow": 4, "run": 8, "sit": 1, "sleep": 1, "sleep-2": 1, "stretch": 13, "walk": 8 } },
  "cat-03": { cat: "pets", frame: 50, scale: 4, cx: 25, foot: 32, ch: 14, anims: { "idle": 10, "lick": 5, "lick-2": 5, "lie": 8, "meow": 4, "run": 8, "sit": 1, "sleep": 1, "sleep-2": 1, "stretch": 13, "walk": 8 } },
  "cat-04": { cat: "pets", frame: 50, scale: 4, cx: 26, foot: 32, ch: 16, anims: { "idle": 10, "itch": 2, "lick": 5, "lick-2": 5, "lie": 8, "meow": 4, "run": 8, "sit": 1, "sleep": 1, "sleep-2": 1, "stretch": 13, "walk": 8 } },
  "cat-05": { cat: "pets", frame: 50, scale: 4, cx: 25, foot: 32, ch: 16, anims: { "idle": 10, "itch": 2, "lick": 5, "lick-2": 5, "lie": 8, "meow": 4, "run": 8, "sit": 1, "sleep": 1, "sleep-2": 1, "stretch": 13, "walk": 8 } },
  "cat-06": { cat: "pets", frame: 50, scale: 4, cx: 25, foot: 32, ch: 14, anims: { "idle": 10, "itch": 2, "lick": 5, "lick-2": 5, "lie": 8, "meow": 4, "run": 8, "sit": 1, "sleep": 1, "sleep-2": 1, "stretch": 13, "walk": 8 } },
  "cat-07": { cat: "pets", frame: 48, scale: 3, cx: 19, foot: 48, ch: 23, anims: { "idle": 4, "walk": 6 } },
  "cat-08": { cat: "pets", frame: 48, scale: 3, cx: 18, foot: 48, ch: 19, anims: { "idle": 4, "walk": 6 } },
  "dog-akita": { cat: "pets", frame: 100, scale: 4, cx: 50, foot: 58, ch: 15, anims: { "bark": 3, "idle": 10, "itch": 2, "lick": 4, "lick-2": 4, "lie": 7, "run": 8, "sit": 1, "sleep": 1, "stretch": 10, "walk": 8 } },
  "dog-doberman": { cat: "pets", frame: 48, scale: 2, cx: 18, foot: 48, ch: 31, anims: { "idle": 4, "walk": 6 } },
  "dog-golden-retriever": { cat: "pets", frame: 100, scale: 3, cx: 50, foot: 61, ch: 22, anims: { "bark": 3, "idle": 10, "itch": 2, "lick": 4, "lick-2": 4, "lie": 7, "run": 8, "sit": 1, "sleep": 1, "stretch": 10, "walk": 8 } },
  "dog-great-dane": { cat: "pets", frame: 100, scale: 2, cx: 50, foot: 67, ch: 34, anims: { "bark": 3, "idle": 10, "itch": 2, "lick": 4, "lick-2": 4, "lie": 7, "run": 8, "sit": 1, "sleep": 1, "stretch": 10, "walk": 8 } },
  "dog-husky": { cat: "pets", frame: 100, scale: 2, cx: 50, foot: 62, ch: 24, anims: { "bark": 3, "idle": 10, "itch": 2, "lick": 4, "lick-2": 4, "lie": 7, "run": 8, "sit": 1, "sleep": 1, "stretch": 10, "walk": 8 } },
  "dog-saint-bernard": { cat: "pets", frame: 100, scale: 2, cx: 50, foot: 65, ch: 29, anims: { "bark": 3, "idle": 10, "itch": 2, "lick": 4, "lick-2": 4, "lie": 7, "run": 8, "sit": 1, "sleep": 1, "stretch": 10, "walk": 8 } },
  "dog-schnauzer": { cat: "pets", frame: 100, scale: 3, cx: 50, foot: 62, ch: 23, anims: { "bark": 3, "idle": 10, "itch": 2, "lick": 4, "lick-2": 4, "lie": 7, "run": 8, "sit": 1, "sleep": 1, "stretch": 10, "walk": 8 } },
  "dog-shiba": { cat: "pets", frame: 48, scale: 2, cx: 20, foot: 48, ch: 25, anims: { "idle": 4, "walk": 6 } },
  "frog-blue-blue": { cat: "pets", frame: 48, scale: 4, cx: 21, foot: 33, ch: 16, anims: { "idle": 8 } },
  "frog-blue-brown": { cat: "pets", frame: 48, scale: 4, cx: 21, foot: 33, ch: 16, anims: { "idle": 8 } },
  "frog-green-blue": { cat: "pets", frame: 48, scale: 4, cx: 21, foot: 33, ch: 16, anims: { "idle": 8 } },
  "frog-green-brown": { cat: "pets", frame: 48, scale: 4, cx: 21, foot: 33, ch: 16, anims: { "idle": 8 } },
  "frog-purple-blue": { cat: "pets", frame: 48, scale: 4, cx: 21, foot: 33, ch: 16, anims: { "idle": 8 } },
  "frog-purple-white": { cat: "pets", frame: 48, scale: 4, cx: 21, foot: 33, ch: 16, anims: { "idle": 8 } },
  "hyena": { cat: "pets", frame: 48, scale: 2, cx: 29, foot: 48, ch: 28, anims: { "idle": 4, "walk": 6 } },
  "rat-01": { cat: "pets", frame: 32, scale: 4, cx: 13, foot: 32, ch: 9, anims: { "idle": 4, "walk": 4 } },
  "rat-02": { cat: "pets", frame: 32, scale: 4, cx: 13, foot: 32, ch: 6, anims: { "idle": 4, "walk": 4 } },
  "scorpion": { cat: "pets", frame: 48, scale: 3, cx: 30, foot: 48, ch: 23, anims: { "idle": 4, "walk": 4 } },
  "snake": { cat: "pets", frame: 48, scale: 4, cx: 33, foot: 48, ch: 15, anims: { "idle": 4, "walk": 4 } },
  "vulture": { cat: "pets", frame: 48, scale: 2, cx: 30, foot: 48, ch: 26, anims: { "idle": 4, "walk": 4 } },
  "biker": { cat: "humans", frame: 48, scale: 2, cx: 13, foot: 48, ch: 34, anims: { "attack": 6, "attack-2": 8, "attack-3": 8, "double-jump": 6, "idle": 4, "jump": 4, "punch": 6, "run": 6, "run-attack": 6 } },
  "cyborg": { cat: "humans", frame: 48, scale: 2, cx: 12, foot: 48, ch: 35, anims: { "attack": 6, "attack-2": 8, "attack-3": 8, "double-jump": 6, "idle": 4, "jump": 4, "punch": 6, "run": 6, "run-attack": 6 } },
  "evil-wizard": { cat: "humans", frame: 140, scale: 1, cx: 73, foot: 97, ch: 53, anims: { "idle": 10, "run": 8, "walk": 8 } },
  "huntress": { cat: "humans", frame: 100, scale: 2, cx: 51, foot: 67, ch: 36, anims: { "attack": 6, "idle": 10, "run": 8 } },
  "martial-hero": { cat: "humans", frame: 126, scale: 2, cx: 68, foot: 82, ch: 39, anims: { "attack": 7, "attack-2": 6, "attack-3": 9, "idle": 10, "run": 8 } },
  "punk": { cat: "humans", frame: 48, scale: 2, cx: 13, foot: 48, ch: 34, anims: { "attack": 6, "attack-2": 8, "attack-3": 8, "double-jump": 6, "idle": 4, "jump": 4, "punch": 6, "run": 6, "run-attack": 6 } },};

/* which sheet variants can stand in for a species; absent = emoji placeholder */
export const SPECIES_SPRITES: Record<string, string[]> = {
  dog: ["dog-golden-retriever", "dog-akita", "dog-great-dane", "dog-schnauzer",
        "dog-saint-bernard", "dog-husky", "dog-shiba", "dog-doberman"],
  cat: ["cat-01", "cat-02", "cat-03", "cat-04", "cat-05", "cat-06", "cat-07", "cat-08"],
  bird: ["bird-crow", "bird-pigeon"],
  frog: ["frog-blue-blue", "frog-blue-brown", "frog-green-blue",
         "frog-green-brown", "frog-purple-blue", "frog-purple-white"],
  bat: ["bat-albino", "bat-fire", "bat-root", "bat-standard", "bat-vampire", "bat-zombie"],
  rat: ["rat-01", "rat-02"],
  hyena: ["hyena"],
  scorpion: ["scorpion"],
  snake: ["snake"],
  vulture: ["vulture"],
};

export const HUMAN_SPRITES = Object.keys(SPRITES).filter(id => SPRITES[id].cat === "humans");

const FRAME_MS = 120; // per animation frame

/* Animated strip element. (x%, y%) matches the emoji sprites' anchor —
 * roughly the top-left of a ~40px emoji — so the artwork's feet are placed
 * at anchor + (20px, 44px), same as an emoji's feet. */
export function spriteImg(id: string, anim: string, x: number, y: number, opts: SpriteOpts = {}): string | null {
  const s = SPRITES[id];
  if (!s) return null;
  const a = s.anims[anim] ? anim : (s.anims.idle ? "idle" : Object.keys(s.anims)[0]);
  const frames = s.anims[a];
  const k = opts.scale || s.scale;
  const px = s.frame * k;
  const style = [
    `width:${px}px`, `height:${px}px`,
    `background-image:url(${import.meta.env.BASE_URL}assets/sprites/${s.cat}/${id}/${a}.png)`,
    `background-size:${frames * px}px ${px}px`,
    `--shift:${-frames * px}px`,
    `animation-duration:${frames * FRAME_MS}ms`,
    `animation-timing-function:steps(${frames})`,
    `margin-left:${Math.round(20 - s.cx * k)}px`,
    `margin-top:${Math.round(44 - s.foot * k)}px`,
    opts.flip ? "scale:-1 1" : "",
  ].join(";");
  const status = opts.status
    ? `<span class="s-status" style="top:${Math.round(44 - (s.ch * k) - 30)}px;left:${20 + Math.round(s.ch * k * 0.4)}px;right:auto">${opts.status}</span>`
    : "";
  return `<div class="sprite${opts.enter ? " enter" : ""}" style="left:${x}%;top:${y}%">
    ${status}<div class="s-px" style="${style}"></div></div>`;
}
